apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: backend
      image: localhost/backend:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
        - containerPort: 5001
          hostPort: 5001
      volumeMounts:
        - mountPath: /app
          name: backend-code
        - mountPath: /app/snapshots
          name: snapshots-volume
  volumes:
    - name: backend-code
      hostPath:
        path: /home/joseph/Smart_Mattress_web_podman/backend
        type: Directory
    - name: snapshots-volume
      hostPath:
        path: /home/joseph/Smart_Mattress_web_podman/snapshots
        type: Directory